class Slot:
    def __init__(self, data: bytes, driver):
        ...
    
    def start(self):
        ...
    
    def run(self, start, deltatime: int):
        ...
    
    def end(self):
        ...